// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI3XjFzEcpqS0mk9ZP_YOFY-ZkZ3W-W8c',
    authDomain: 'smart-shop-330f7.firebaseapp.com',
    projectId: 'smart-shop-330f7',
    storageBucket: 'smart-shop-330f7.appspot.com',
    messagingSenderId: '641900989382',
    appId: '1:641900989382:web:98be970f3e19b99b4c00c7',
    measurementId: 'G-JD1BH1RNLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI3XjFzEcpqS0mk9ZP_YOFY-ZkZ3W-W8c',
    appId: '1:641900989382:android:07acfac047477ce14c00c7',
    messagingSenderId: '641900989382',
    projectId: 'smart-shop-330f7',
    storageBucket: 'smart-shop-330f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBusENYY_9QM5nLi3lMJaCaECAJB2-LhA',
    appId: '1:327324836622:ios:f4c05db96aa86bc36ad5f',
    messagingSenderId: '32732483662',
    projectId: 'eshop-multivendor-new',
    storageBucket: 'eshop-multivendr-new.appspot.com',
    androidClientId:
        '327324836622-0da9k42bkmfgjbkji5a9l2lq37g0tvr.apps.googleusercontent.com',
    iosClientId:
        '327324836622-66keg8mgjde4hd1g14uee9hbks5ngki.apps.googleusercontent.com',
    iosBundleId: 'wrteam.eshop.multivendr',
  );
}
